### ISSUE TITLE
Julia feature request: `Alternative`

### ISSUE THREAD

**Issue by eschnett** [iamed2/ResultTypes.jl#1]
See https://github.com/JuliaLang/julia/issues/17073 -- this feature request is very similar to what you implemented.

**Comment by kmsquire** [comment]
The request here seems to be only abstractly related to `Result` types (as I understand them), and the corresponding Julia issue was closed (with a PR that implements essentially what was requested).

So this can probably be closed.  If something like this is still needed, it should probably live somewhere else (base Julia or a separate package).

`Result` could possibly be implemented using a hypothetical implementation of this, but the compiler is good enough now that the current `Result` type is probably good enough.

**Comment by keorn** [comment]
@0x0f0f0f Maybe this can be closed? @kmsquire summarized it well a while ago.
